# Generated by Django 2.0.7 on 2019-03-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medtitater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('country', models.CharField(max_length=120)),
                ('born', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('phone', models.CharField(max_length=60)),
                ('profession', models.CharField(max_length=60)),
                ('course_type', models.CharField(max_length=60)),
                ('course_date', models.DateField()),
                ('remarks', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
