# Generated by Django 2.0.7 on 2019-03-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meditater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=264)),
                ('course_type', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('gender', models.CharField(max_length=60)),
                ('born', models.CharField(max_length=60)),
                ('profession', models.CharField(max_length=60)),
                ('remarks', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Medtitater',
        ),
    ]
