# Generated by Django 2.0.7 on 2019-03-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditater', '0002_auto_20190315_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditater',
            name='email',
            field=models.EmailField(max_length=60),
        ),
    ]
