# Generated by Django 2.1.7 on 2019-03-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meditater', '0003_auto_20190315_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMeditater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=1000)),
                ('meditater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditaters', to='meditater.Meditater')),
            ],
        ),
    ]
