# Generated by Django 2.1.7 on 2019-03-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meditater', '0004_emailmeditater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmeditater',
            name='meditater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meditater.Meditater'),
        ),
    ]
