# Generated by Django 2.1.7 on 2019-03-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditater', '0006_auto_20190327_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmeditater',
            name='meditater',
        ),
    ]
